### ISSUE TITLE
pROC_analysis error 

### ISSUE THREAD

**Issue by aballou16** [aballou16/geneticriskR#4]
Error: `No valid data provided`

Using a model generated using the test_data:
`simple_mod <- simple_logistic_reg(test_data, hypertension)`
And then using that model in `proc_analysis()` as follows:
`proc_analysis(test_data, hypertension, simple_mod)`
throws the error.

**Comment by beanumber** [comment]
You have to be very careful about how you are passing the name of the variable through `phenotype`. If you want to pass it as a bare name (like in `dplyr`), then you need to make use of tidy evaluation (which is complicated). I'd recommend having it be a `character`. 

If you do `character`, then you have to say `full_data[[phenotype]]` instead of `full_data$phenotype`.

But also, it's probably not necessary, because a `glm` object knows about what it's response and explanatory variables are, and what data it was fed. Check out `simple_mod$terms` and `simple_mod$data`. I think with some clever use of those, `proc_analysis()` only needs the model object and the dots.
